name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter=1.0.0
  - seaborn=0.11.1
  - pandas=1.4.2
  - pip=20.3.3
  - pandas-profiling=3.1.0
  - pyarrow=2.0
  - ipywidgets=8.0.2
  - jinja2=3.0.3
  - pip:
      - wandb==0.12.17 #Need to upgrade wandb library while working on mac silicon processor